# action.yml
name: 'Workflow Status'
description: 'Returns workflow summery status(success, cancelled, failure), in case of failure it also returns the job and step of failure'
inputs:
  workflow_name:  # id of input
    description: 'name of current workflow'
    required: true
    default: '${{ github.workflow }}'  
  github_run_id:  
    description: 'A unique number for each workflow run within a repository.'
    required: true
    default: '${{ github.run_id }}'  
  github_repository:  
    description: 'The owner and repository name.'
    required: true
    default: '${{ github.repository }}'
  github_token:  
    description: 'A token to authenticate on behalf of the GitHub App installed on your repository.'
    required: true
    default: '${{ github.token }}'  
outputs:
  workflow_result: # id of output
    description: 'The result of the current workflow run (success,cancelled,failure)'
  failed_job: 
    description: 'The name of the job that was failed(only if workflow conclusion is failure)'  
  failed_step: 
    description: 'The name of the step that was failed(only if workflow conclusion is failure)'  
  notification_color: 
    description:  'color for slack notification. '
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.workflow_name }}
    - ${{ inputs.github_run_id }}
    - ${{ inputs.github_repository }}
    - ${{ inputs.github_token }}
    
